### ISSUE TITLE
Decimal To Roman Numeral TypeError

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#289]
**Name or Id of generator:**
Decimal To Roman Numeral - 85
**Issue:**
```
Traceback (most recent call last):
  File "makeReadme.py", line 29, in <module>
    prob, solu = myGen()
  File "/home/luke/mathgenerator/mathgenerator/__init__.py", line 26, in __call__
    return self.func(**kwargs)
  File "/home/luke/mathgenerator/mathgenerator/funcs/decimalToRomanNumeralsFunc.py", line 18, in decimalToRomanNumeralsFunc
    solution += (roman_dict[divisor] * roman_dict[divisor * 5])
TypeError: can't multiply sequence by non-int of type 'str'
```

**Comment by Metropass** [comment]
@lukew3  Oh, when you put in the value of 85, it crashes, correct? I'll post a bug-fix for this soon

**Comment by lukew3** [comment]
@Metropass No, 85 is the id of the generator.

**Comment by Metropass** [comment]
Fixed the bug, it should be a PR now.
