### ISSUE TITLE
algebra/expanding string integer out of range error

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#403]
### Bug Description

When generating a problem for algebra/expanding, this error may come up:
```
Traceback (most recent call last):
  File "adoptGenerator.py", line 40, in <module>
    main()  # makes readme
  File "/home/luke/src/mathgenerator/scripts/makeReadme.py", line 134, in main
    write_subject_table(subject, wList)
  File "/home/luke/src/mathgenerator/scripts/makeReadme.py", line 110, in write_subject_table
    write_list.append(gen_to_row_string(item))
  File "/home/luke/src/mathgenerator/scripts/makeReadme.py", line 58, in gen_to_row_string
    prob, solu = myGen()
  File "/home/luke/src/mathgenerator/mathgenerator/generator.py", line 26, in __call__
    return self.func(*args, **kwargs)
  File "/home/luke/src/mathgenerator/mathgenerator/funcs/algebra/expanding.py", line 37, in gen_func
    elif p3[0] == "+":
IndexError: string index out of range
```

**Comment by ialoko** [comment]
Hello,
I just fixed this issue. Would love if I could get this approved for Hacktoberfest 2023
